//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.18 at 12:36:17 PM EST 
//


package Calculator.Calculator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for job complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * <complexType name="job">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="jobID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="question" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="answer" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "job", propOrder = {
    "jobID",
    "question",
    "answer"
})
public class Job {

    protected int jobID;
    protected int question;
    protected int answer;

    /**
     * Gets the value of the jobID property.
     * 
     */
    public int getJobID() {
        return jobID;
    }

    /**
     * Sets the value of the jobID property.
     * 
     */
    public void setJobID(int value) {
        this.jobID = value;
    }

    /**
     * Gets the value of the question property.
     * 
     */
    public int getQuestion() {
        return question;
    }

    /**
     * Sets the value of the question property.
     * 
     */
    public void setQuestion(int value) {
        this.question = value;
    }

    /**
     * Gets the value of the answer property.
     * 
     */
    public int getAnswer() {
        return answer;
    }

    /**
     * Sets the value of the answer property.
     * 
     */
    public void setAnswer(int value) {
        this.answer = value;
    }

}
